import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useState } from "react";
//  import code from '../../public/code.png';
// import dewave from "../../public/dewave.png";

import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillYoutube,
  AiFillLinkedin,
} from "react-icons/ai";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode,setDarkMode] =  useState(false);
  return (
    <div className={darkMode?"Dark":""}>
      <Head>
        <title>Sivagami Portfolio </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-black dark:text-white">
        <section className="">
          <nav className=" py-10 mb--12 flex justify-between">
            <h1 className="text-xl font-burtons md:text-3xl lg:text-5xl " >sivagami</h1>
            <ul className="flex justify-between gap-8">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl " onClick={()=>setDarkMode(!darkMode)} />
              </li>
              <li className="text-xl cursor-pointer text-blue-500 hover:text-green-500">
                Resume
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl text-teal-600 py-5">shivagami Shanti</h2>
            <h3 className="text-3xl py-5">fullstack developer</h3>
            <p className="text-md py-5 text-gray-600 font-medium leading-8">
              Lorem.56Tailwind CSS works by scanning all of your HTML files,
              JavaScript components, and any other templates for class names,
              generating the corresponding styles and then writing them to a
              static CSS file.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 text-blue-600">
            <AiFillLinkedin />
            <AiFillTwitterCircle />
            <AiFillYoutube />
          </div>
          <div className="w-60 h-60 rounded-full bg-blue-300 relative mt-20 mx-auto pt-8 md:w-96 md:h-96">

          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 ">Services I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-700">
              Lorem ipsum Lorem.56Tailw.ind CSS works by scanning all of your
              HTML files, JavaScript components
              <span className="text-teal-800 hover:text-red-500 cursor-pointer">
                Color Word
              </span>
              , and any other templates for class names, generating the
              corresponding styles and then writing them to a static
              <span className="text-teal-800 hover:text-red-500 cursor-pointer">
                Color Word
              </span>
              CSS file.
            </p>
            <p className="text-md py-2 leading-8 text-gray-700">
              Lorem .300 Lorem.56Tailwind CSS works by scanning all of your HTML
              files, JavaScript components, and any other templates for class
              names, generating the corresponding styles and then writing them
              to a static CSS file.
            </p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-r-xl my-10">
            {/* <image src={code.png}/> */}
            <h3 className="text-lg font-md ">React about description</h3>
            <p className="py-2 ">
              Lorem.200 Lorem .300 Lorem.56Tailwind CSS works by scanning all of
              your HTML files, JavaScript components, and any other templates
              for class names, generating the corresponding styles and then
              writing them to a static CSS file.
            </p>
            <h4 className="py-4 text-teal-600">tools i use</h4>
            <p className="text-gray-800 py-1">hooks</p>
            <p className="text-gray-800 py-1">context</p>
            <p className="text-gray-800 py-1">state</p>
          </div>
        </section>
        <section>
          <h3 className="text-3xl py-1">Portfolio</h3>
          <p className="text-md py-2 leading-8 text-gray-700">Lorem.300</p>
          <div>
            <div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
